# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/Projects/chip8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/Projects/chip8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Projects/chip8/CMakeFiles /storage/emulated/0/Projects/chip8//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Projects/chip8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CHIP-8

# Build rule for target.
CHIP-8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CHIP-8
.PHONY : CHIP-8

# fast build rule for target.
CHIP-8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHIP-8.dir/build.make CMakeFiles/CHIP-8.dir/build
.PHONY : CHIP-8/fast

src/core.o: src/core.cpp.o
.PHONY : src/core.o

# target to build an object file
src/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHIP-8.dir/build.make CMakeFiles/CHIP-8.dir/src/core.cpp.o
.PHONY : src/core.cpp.o

src/core.i: src/core.cpp.i
.PHONY : src/core.i

# target to preprocess a source file
src/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHIP-8.dir/build.make CMakeFiles/CHIP-8.dir/src/core.cpp.i
.PHONY : src/core.cpp.i

src/core.s: src/core.cpp.s
.PHONY : src/core.s

# target to generate assembly for a file
src/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHIP-8.dir/build.make CMakeFiles/CHIP-8.dir/src/core.cpp.s
.PHONY : src/core.cpp.s

src/getfont.o: src/getfont.cpp.o
.PHONY : src/getfont.o

# target to build an object file
src/getfont.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHIP-8.dir/build.make CMakeFiles/CHIP-8.dir/src/getfont.cpp.o
.PHONY : src/getfont.cpp.o

src/getfont.i: src/getfont.cpp.i
.PHONY : src/getfont.i

# target to preprocess a source file
src/getfont.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHIP-8.dir/build.make CMakeFiles/CHIP-8.dir/src/getfont.cpp.i
.PHONY : src/getfont.cpp.i

src/getfont.s: src/getfont.cpp.s
.PHONY : src/getfont.s

# target to generate assembly for a file
src/getfont.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHIP-8.dir/build.make CMakeFiles/CHIP-8.dir/src/getfont.cpp.s
.PHONY : src/getfont.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CHIP-8"
	@echo "... src/core.o"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/getfont.o"
	@echo "... src/getfont.i"
	@echo "... src/getfont.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

